In [1]:
%matplotlib qt5

import sys

sys.path.append('/home/ABTLUS/thales.bastos/repos/pack_thales')
    
from touschek_pack import Classes
from touschek_pack import functions

import pymodels
import pyaccel
import numpy as np
import matplotlib.pyplot as plt

In [2]:
acc = pymodels.si.create_accelerator()
acc = pymodels.si.fitted_models.vertical_dispersion_and_coupling(acc)
spos = pyaccel.lattice.find_spos(acc, indices='open')
tousan = Classes.Tous_analysis(acc)

In [3]:
tousan.get_amps_idxs()

(True,
 (array([-0.04372908, -0.04372908, -0.04372908, ..., -0.04372908,
         -0.04372908, -0.04372908]),
  array([0.04372908, 0.04372908, 0.04372908, ..., 0.04372908, 0.04372908,
         0.04372908])),
 (array([0.00000000e+00, 1.00036646e-01, 2.00073292e-01, ...,
         5.18189827e+02, 5.18289863e+02, 5.18389900e+02]),
  array([0.04372908, 0.04372908, 0.04372908, ..., 0.04372908, 0.04372908,
         0.04372908]),
  array([-0.04372908, -0.04372908, -0.04372908, ..., -0.04372908,
         -0.04372908, -0.04372908])))

In [7]:
fam_data = pymodels.si.get_family_data(acc)

In [16]:
fam_data['QDB1']['index'][4]

[1608]

In [4]:
model = pymodels.si.create_accelerator()
model.cavity_on = True
model.radiation_on = True
model.vchamber_on = True

accep= pyaccel.optics.calc_touschek_energy_acceptance(model)

In [17]:
s = [spos[1608]]
tousan.plot_analysis_at_position(s, 'pos', accep)