In [1]:
%matplotlib qt5

import sys

sys.path.append('/home/ABTLUS/thales.bastos/repos/pack_thales')
    
from touschek_pack import Classes
from touschek_pack import functions

import pymodels
import pyaccel
import numpy as np
import matplotlib.pyplot as plt

In [2]:
acc = pymodels.si.create_accelerator()
acc = pymodels.si.fitted_models.vertical_dispersion_and_coupling(acc)
tousan = Classes.Tous_analysis(acc)

In [3]:
tousan.get_amps_idxs()

(True,
 (array([-0.04372908, -0.04372908, -0.04372908, ..., -0.04372908,
         -0.04372908, -0.04372908]),
  array([0.04372908, 0.04372908, 0.04372908, ..., 0.04372908, 0.04372908,
         0.04372908])),
 (array([0.00000000e+00, 1.00036646e-01, 2.00073292e-01, ...,
         5.18189827e+02, 5.18289863e+02, 5.18389900e+02]),
  array([0.04372908, 0.04372908, 0.04372908, ..., 0.04372908, 0.04372908,
         0.04372908]),
  array([-0.04372908, -0.04372908, -0.04372908, ..., -0.04372908,
         -0.04372908, -0.04372908])))

In [4]:
# spos = pyaccel.lattice.find_spos(acc, indices='closed')
# pyaccel.lattice.find_indices(acc, 'fam_name', 'Q1'), spos[70]

# agora o que eu preciso fazer é 

In [4]:
spos = pyaccel.lattice.find_spos(acc, indices='open')
s = 5.5
res = tousan.fast_aquisition(s, 'pos')

In [5]:
a, fp, dp = res


In [6]:
plt.figure()
plt.plot(dp, fp)

plt.xlim(-0.1,0.4)

(-0.1, 0.4)

In [12]:
index = np.argmin(np.abs(spos-s))
accep=pyaccel.optics.calc_touschek_energy_acceptance(acc)


In [22]:

np.where(fp > 1e-19)[0]
# indx = np.int0()




array([], dtype=int64)

(-0.1, 0.3)

In [13]:
functions.plot_track(acc, a, np.int0(tousan.inds_pos), tousan.off_energy, 'pos', index, accep, dp, fp)

In [11]:

model = pymodels.si.create_accelerator()
model.cavity_on = False # a forma como as aceitancias eram calculadas eram por meio de 
model.radiation_on = False
accep = pyaccel.optics.calc_touschek_energy_acceptance(model) 

In [15]:

ind = np.argmin(np.abs(tousan._spos - s))
functions.plot_track(acc, a, np.int0(tousan._inds_pos), tousan._off_energy,'pos', ind, accep,
                     dp[indx],fp[indx])

In [ ]:
acc = pymodels.si.create_accelerator()

acc = pymodels.si.fitted_models.vertical_dispersion_and_coupling(acc)

In [ ]:
model = pymodels.si.create_accelerator()
model.cavity_on = True
model.radiation_on = True
model.vchamber_on = True

deltas = np.linspace(0,0.1, 500)
lspos = [30, 50]

var = functions.trackm_elec(model, deltas,6,lspos)

In [ ]:
var[1]

In [ ]:


tousan = Classes.Tous_analysis(acc)

tousan.nturns = 10
tousan.deltas = np.linspace(0,0.1,500)
hpos = tousan.h_pos
hneg = tousan.h_neg
tousan.accep
tousan._sc_accps


In [ ]:
fp,fn,dp,dn = tousan.fast_aquisition(30, 'pos')

In [ ]:
fam = pymodels.si.get_family_data(acc)
fam['SRFCav']

In [ ]:
acc = pymodels.si.create_accelerator()

print(acc)

In [ ]:

plt.figure()
plt.plot(dp,fp)

plt.xlim(0,10)
plt.show()

In [ ]:
acc = pymodels.si.create_accelerator()

acc.cavity_on = False
acc.radiation_on = False
acc.vchamber_on = False

hpos = pyaccel.lattice.get_attribute(acc, 'hmax', indices='closed')
hneg = pyaccel.lattice.get_attribute(acc, 'hmin', indices='closed')