In [1]:
# pip install seaborn

In [3]:
%matplotlib qt5
import pyaccel
import pymodels
import numpy as np
import matplotlib.pyplot as plt
import scipy.integrate as scyint
import pandas as pd
from mathphys import constants
from mathphys.functions import save_pickle, load_pickle
from mathphys.beam_optics import beam_rigidity

import touschek_pack.functions as tousfunc
import touschek_pack.Classes as tousclass



In [4]:
acc = pymodels.si.create_accelerator()
acc = pymodels.si.fitted_models.vertical_dispersion_and_coupling(acc)

tousan = tousclass.Tous_analysis(acc)
spos = pyaccel.lattice.find_spos(acc, indices='closed')



# BC, Q1, B1
# s_test = [12.4387475, 6.8607475, 5.3, 7.3207475]
# fam_data = pymodels.si.get_family_data(acc)


In [5]:
# s = spos
# dic = tousan.get_reordered_dict(s, 'lost_positions')

In [6]:
# pic_scat = save_pickle(dic, fname='pic_scat')

In [7]:
dic = load_pickle('pic_scat.pickle')

In [ ]:
tousan.get_lost_profile(dic)

In [6]:
tousan.plot_scat_table(spos, dic,1,1)

In [33]:
list(a.columns)

['0.0',
 '1.91',
 '2.31',
 '2.37',
 '2.42',
 '2.57',
 '3.02',
 '3.52',
 '3.65',
 '3.8',
 '3.95',
 '4.15',
 '4.23',
 '4.32',
 '4.39',
 '4.54',
 '4.69',
 '4.83',
 '4.97',
 '5.02',
 '5.06',
 '5.1',
 '5.11',
 '5.15',
 '5.2',
 '5.3',
 '5.45',
 '5.49',
 '5.5',
 '5.51',
 '5.52',
 '5.53',
 '5.54',
 '5.55',
 '5.59',
 '5.74',
 '5.84',
 '5.89',
 '5.92',
 '5.94',
 '5.98',
 '6.02',
 '6.07',
 '6.54',
 '6.69',
 '6.86',
 '7.06',
 '7.2',
 '7.32',
 '7.47',
 '7.7',
 '7.9',
 '8.07',
 '8.22',
 '8.43',
 '8.44',
 '8.47',
 '8.5',
 '8.53',
 '8.55',
 '8.57',
 '8.58',
 '8.6',
 '8.77',
 '8.95',
 '8.96',
 '8.97',
 '8.98',
 '8.99',
 '9.0',
 '9.05',
 '9.18',
 '9.3',
 '9.36',
 '9.37',
 '9.38',
 '9.39',
 '9.4',
 '9.41',
 '9.58',
 '9.76',
 '9.78',
 '9.79',
 '9.8',
 '9.82',
 '9.85',
 '9.88',
 '9.92',
 '10.25',
 '10.4',
 '10.57',
 '10.77',
 '11.0',
 '11.15',
 '11.41',
 '11.61',
 '11.81',
 '11.96',
 '12.16',
 '12.24',
 '12.36',
 '12.44',
 '12.47',
 '12.49',
 '12.5',
 '12.52',
 '12.68',
 '12.84',
 '12.87',
 '12.9',
 '12.91

In [6]:
# df = pd.DataFrame(dic)
# a = df.set_index('lost_positions')

# summed = []
# for idx, iten in a.iterrows():
#     sum_row = a.loc[idx][:].sum()
#     summed.append(sum_row)

# plt.figure()
# plt.scatter(list(a.index), summed)

In [8]:
# tousan.plot_scat_table(spos, dic, n_c=1, n_r=1)

In [4]:
# indices = fam_data['QN']['index']

# for index_list in indices:
#     init, final = index_list[0], index_list[-1]
#     s = spos[init:final]
#     tousan.plot_scat_table(s, n_c=1, n_r=1)

In [17]:
print(acc[29])

fam_name   : B1 
pass_method: bnd_mpole_symplectic4_pass 
length     : 0.05 m
angle      : 6.789330790257942e-05 rad
polynom_b  : [ 0.0000e+00 -1.0742e-03 -9.8271e-02  5.0359e-02 -1.0312e+01  9.0013e+02
  8.2477e+04] 1/m¹, 1/m², 1/m³, ...
vchamber   : 2 
hmin       : -0.012 m
hmax       : 0.012 m
vmin       : -0.012 m
vmax       : 0.012 m


In [22]:
# len(indices)

hp, hn, ind = tousfunc.histgms(acc, s_test, 50000, tousan.accep, 1e-4, True)

0.9998942037094188
0.9996541142288773
0.999734763273008
0.9995976074018468


In [23]:
plt.figure()
plt.hist(hp[2], bins=200, density=True)
plt.hist(hn[2], bins=200, density=True)
plt.show()

In [11]:
fam_data = pymodels.si.get_family_data(acc)

In [12]:
envelopes = pyaccel.optics.calc_beamenvelope(acc)
len(envelopes)

6550

In [13]:
tousan.accep


(array([-0.04372908, -0.04372908, -0.04372908, ..., -0.04372908,
        -0.04372908, -0.04372908]),
 array([0.04372908, 0.04372908, 0.04372908, ..., 0.04372908, 0.04372908,
        0.04372908]))

In [14]:
tousan._accep

(array([-0.04372908, -0.04372908, -0.04372908, ..., -0.04372908,
        -0.04372908, -0.04372908]),
 array([0.04372908, 0.04372908, 0.04372908, ..., 0.04372908, 0.04372908,
        0.04372908]))

In [19]:
tousan.plot_normtousd(s_test)

In [16]:
spos[np.intp(pyaccel.lattice.find_indices(acc, 'fam_name', 'SFA1'))]

array([  7.3207475,  96.2072325, 110.9987275, 199.8852125, 214.6767075,
       303.5631925, 318.3546875, 407.2411725, 422.0326675, 510.9191525])

In [17]:
np.intp(pyaccel.lattice.find_indices(acc, 'fam_name', 'SFA1'))

array([  74, 1238, 1374, 2538, 2672, 3846, 3982, 5154, 5297, 6470])

In [27]:
array  = np.array([1,54,7,8,4,7,4,8,9,6,3,3,8,57,45,3,7756,8,34,5])
a = 8 

np.where(array == a)[0]

array([ 3,  7, 12, 17])

In [ ]:
tousfunc.histgms(acc, )