In [1]:
%matplotlib qt5

In [2]:
import pyaccel
import pymodels
import numpy as np
import matplotlib.pyplot as plt
import scipy.integrate as scyint
import pandas as pd

In [3]:
import touschek_pack.functions as tousfunc

In [4]:
import touschek_pack.Classes as tousclass

In [5]:
acc = pymodels.si.create_accelerator()
acc = pymodels.si.fitted_models.vertical_dispersion_and_coupling(acc)
ltime = pyaccel.lifetime.Lifetime(acc)

In [6]:
rate = ltime.touschek_data['rate']
spos = pyaccel.lattice.find_spos(acc, indices='closed')
accep = pyaccel.optics.calc_touschek_energy_acceptance(acc)

In [7]:
get_sc = tousfunc.get_scaccep(acc, accep)


In [8]:
scalc, daccp, daccn = get_sc

In [9]:
acc = pymodels.si.create_accelerator()
acc = pymodels.si.fitted_models.vertical_dispersion_and_coupling(acc)

tousan = tousclass.Tous_analysis(acc)

In [10]:
# lembre-se que queremos contruir uma função que transforme dados que eu já possuo em tabelas
# uma biblioteca bastante util para isso seria a bib pandas
# vamos tentar usar ela para nossos calculos

s = [spos[1046]]

ress = tousan.fast_aquisition(s, 'pos')

In [11]:
res, fp, dp = ress

In [12]:
dataframe = pd.DataFrame({'touschek_dens': fp, 'energy_dev':dp})

In [13]:
# para este caso específico a posição analisada é spos[1046], ou seja, o indice em que a simulação tracking começa é em 1046
# a para este valor teremos então diversas posições em que o eletron é perdido e a partir disso eu vou ter organizar meu pensamento

lostinds, deltas = np.zeros(len(res)), np.zeros(len(res))
for idx,iten in enumerate(res):
    tloss, ellost, delta = iten
    lostinds[idx] = ellost
    deltas[idx] = delta

# deltas são os desvios de energia perdidos pelo tracking


In [ ]:
lost_pos = spos[np.intp(lostinds)]

In [92]:
# o que precisamos fazer seria, uma forma de definir os elementos do array como sendo os intervalos em que os desvios de energia estarão inseridos
# se eu tenho n elementos dentro do meu array então eu vou ter n-1 intervalos para analisar

# esse interv_delta_tracking é definido como sendo os intervalos de desvio de energia onde os elétrons vão se perdendo

step = int((deltas[0]+deltas[-1])/0.03)
interv_delta_tracking = np.linspace(deltas[0], deltas[-1], step)

# então é ai que vem entra o cats jump kk, temos realmente que contar a quantidade de particulas perdidas em cada intervalo de desvio de energia

# é que na verdade os desvios de energia que eu estou querendo contar em cada intervalo são os próprios deltas


In [108]:
from itertools import groupby

In [123]:
lostinds = np.intp(lostinds)
groups = [list(group) for key, group in groupby(lostinds)]

# agora que eu agrupei em elementos iguais eu também preciso agrupar os deltas correspondentes as posições s do anel onde esses elétrons foram perdidos

# como fazer isso em 


In [153]:
def extract_delt(groups, deltas):
    c = 0
    big_list = []
    for lists in groups:
        lil_list = []
        for _ in lists:
            lil_list.append(c)
            c+=1
            
        big_list.append(lil_list)
    
    sep_deltas = []

    for iten in big_list:
        sep_deltas.append(deltas[iten])

    return sep_deltas


In [154]:
smidx = extract_delt(groups,deltas)

In [28]:
# eu quero pegar todos os desvios de energia que se encontram dentro de um determinado intervalo que esta sendo definido pela
# variável interv

# como eu posso fazer isso ?

# com certeza fazer um for não é a melhor opção, porque deve existir alguma função numpy que faça esse trabalho de forma mais otimizada
array = [1, 2, 3, 4, 5]

# Crie um iterador deslocado do array

    

Item Atual: 0.02909358829884054, Próximo Item: 0.032626381163699744
Item Atual: 0.032626381163699744, Próximo Item: 0.036159174028558956
Item Atual: 0.036159174028558956, Próximo Item: 0.03969196689341817
Item Atual: 0.03969196689341817, Próximo Item: 0.04322475975827737
Item Atual: 0.04322475975827737, Próximo Item: 0.04675755262313658
Item Atual: 0.04675755262313658, Próximo Item: 0.05029034548799579
Item Atual: 0.05029034548799579, Próximo Item: 0.053823138352855
Item Atual: 0.053823138352855, Próximo Item: 0.05735593121771421
Item Atual: 0.05735593121771421, Próximo Item: 0.06088872408257341
Item Atual: 0.06088872408257341, Próximo Item: 0.06442151694743262
Item Atual: 0.06442151694743262, Próximo Item: 0.06795430981229184
Item Atual: 0.06795430981229184, Próximo Item: 0.07148710267715104
Item Atual: 0.07148710267715104, Próximo Item: 0.07501989554201025
Item Atual: 0.07501989554201025, Próximo Item: 0.07855268840686946
Item Atual: 0.07855268840686946, Próximo Item: 0.0820854812717

In [14]:
tousan.get_amps_idxs()

(True,
 (array([-0.04372908, -0.04372908, -0.04372908, ..., -0.04372908,
         -0.04372908, -0.04372908]),
  array([0.04372908, 0.04372908, 0.04372908, ..., 0.04372908, 0.04372908,
         0.04372908])),
 (array([0.00000000e+00, 1.00036646e-01, 2.00073292e-01, ...,
         5.18189827e+02, 5.18289863e+02, 5.18389900e+02]),
  array([0.04372908, 0.04372908, 0.04372908, ..., 0.04372908, 0.04372908,
         0.04372908]),
  array([-0.04372908, -0.04372908, -0.04372908, ..., -0.04372908,
         -0.04372908, -0.04372908])))

In [ ]:
accep = pyaccel.optics.calc_touschek_energy_acceptance(acc)

In [ ]:
tousan.plot_analysis_at_position([spos[1046]], 'pos', accep)