In [1]:
%matplotlib qt5

In [2]:
import pyaccel
import pymodels
import numpy as np
import matplotlib.pyplot as plt
import scipy.integrate as scyint
import pandas as pd

In [3]:
import touschek_pack.functions as tousfunc

In [4]:
import touschek_pack.Classes as tousclass

In [5]:
acc = pymodels.si.create_accelerator()
acc = pymodels.si.fitted_models.vertical_dispersion_and_coupling(acc)
ltime = pyaccel.lifetime.Lifetime(acc)

In [14]:
rate = ltime.touschek_data['rate']

spos = pyaccel.lattice.find_spos(acc, indices='closed')

accep = pyaccel.optics.calc_touschek_energy_acceptance(acc)

In [15]:
get_sc = tousfunc.get_scaccep(acc, accep)


In [16]:
scalc, daccp, daccn = get_sc

In [21]:
ltime.touschek_data

{'rate': array([4.81650628e-10, 4.74269276e-10, 4.67035040e-10, ...,
        4.79696053e-10, 4.80696668e-10, 4.81650628e-10]),
 'avg_rate': 3.184266945178688e-06,
 'volume': array([6.61909476e-13, 6.67803553e-13, 6.73709370e-13, ...,
        6.62894710e-13, 6.62373907e-13, 6.61909476e-13]),
 'pos': array([0.00000000e+00, 1.00036646e-01, 2.00073292e-01, ...,
        5.18189827e+02, 5.18289863e+02, 5.18389900e+02]),
 'touschek_coeffs': {'b1': array([10922.96480184, 11083.86010819, 11247.95795055, ...,
         10946.14256218, 10933.160214  , 10922.96480184]),
  'b2': array([8920.00594302, 9079.54334195, 9242.28327009, ..., 8942.59471841,
         8929.90686774, 8920.00594302]),
  'taum_p': array([0.00344115, 0.00344115, 0.00344115, ..., 0.00344115, 0.00344115,
         0.00344115]),
  'taum_n': array([0.00344115, 0.00344115, 0.00344115, ..., 0.00344115, 0.00344115,
         0.00344115]),
  'f_int_p': array([[0.00031958, 0.00031749, 0.00031541, ..., 0.00031876, 0.00031917,
          0.000

In [8]:
spos = pyaccel.lattice.find_spos(acc, indices='open')

In [6]:
acc = pymodels.si.create_accelerator()
acc = pymodels.si.fitted_models.vertical_dispersion_and_coupling(acc)

tousan = tousclass.Tous_analysis(acc)

In [9]:
# lembre-se que queremos contruir uma função que transforme dados que eu já possuo em tabelas
# uma biblioteca bastante util para isso seria a bib pandas
# vamos tentar usar ela para nossos calculos

s = [spos[1046]]

ress = tousan.fast_aquisition(s, 'pos')

In [10]:
res, fp, dp = ress

In [11]:
dataframe = pd.DataFrame({'touschek_dens': fp, 'energy_dev':dp})

In [74]:
dataframe = dataframe.set_index((dataframe.columns[0]))


In [13]:
# para este caso específico a posição analisada é spos[1046], ou seja, o indice em que a simulação tracking começa é em 1046
# a para este valor teremos então diversas posições em que o eletron é perdido e a partir disso eu vou ter organizar meu pensamento

lostinds, deltas = np.zeros(len(res)), np.zeros(len(res))
for idx,iten in enumerate(res):
    tloss, ellost, delta = iten
    lostinds[idx] = ellost
    deltas[idx] = delta



In [19]:
lost_pos = spos[np.intp(lostinds)]


In [37]:
df = pd.DataFrame({'spos[1046]':lost_pos, 'energy_dev': deltas})

In [38]:
df.transpose()

0          1           2           3           4    \
spos[1046]  99.525233  99.443233  514.237152  514.237152  514.155152   
energy_dev   0.029094   0.029476    0.029859    0.030242    0.030625   

                   5           6           7           8           9    ...  \
spos[1046]  514.071152  514.071152  513.997152  513.847152  513.847152  ...   
energy_dev    0.031008    0.031390    0.031773    0.032156    0.032539  ...   

                  314        315        316        317        318        319  \
spos[1046]  88.010233  88.010233  88.010233  88.010233  88.010233  88.010233   
energy_dev   0.149296   0.149679   0.150062   0.150444   0.150827   0.151210   

                  320        321        322        323  
spos[1046]  88.010233  88.010233  88.010233  88.010233  
energy_dev   0.151593   0.151976   0.152359   0.152741  

[2 rows x 324 columns]

In [65]:
step = int((deltas[0]+deltas[-1])/0.005)
interv = np.linspace(deltas[0], deltas[-1], step)

In [69]:
interv, step

(array([0.02909359, 0.03262638, 0.03615917, 0.03969197, 0.04322476,
        0.04675755, 0.05029035, 0.05382314, 0.05735593, 0.06088872,
        0.06442152, 0.06795431, 0.0714871 , 0.0750199 , 0.07855269,
        0.08208548, 0.08561827, 0.08915107, 0.09268386, 0.09621665,
        0.09974945, 0.10328224, 0.10681503, 0.11034782, 0.11388062,
        0.11741341, 0.1209462 , 0.124479  , 0.12801179, 0.13154458,
        0.13507737, 0.13861017, 0.14214296, 0.14567575, 0.14920855,
        0.15274134]),
 36)

In [27]:
tousan.get_amps_idxs()

(True,
 (array([-0.04372908, -0.04372908, -0.04372908, ..., -0.04372908,
         -0.04372908, -0.04372908]),
  array([0.04372908, 0.04372908, 0.04372908, ..., 0.04372908, 0.04372908,
         0.04372908])),
 (array([0.00000000e+00, 1.00036646e-01, 2.00073292e-01, ...,
         5.18189827e+02, 5.18289863e+02, 5.18389900e+02]),
  array([0.04372908, 0.04372908, 0.04372908, ..., 0.04372908, 0.04372908,
         0.04372908]),
  array([-0.04372908, -0.04372908, -0.04372908, ..., -0.04372908,
         -0.04372908, -0.04372908])))

In [31]:
accep = pyaccel.optics.calc_touschek_energy_acceptance(acc)

In [33]:
tousan.plot_analysis_at_position([spos[1046]], 'pos', accep)